export const RJSF_ADD_FORM = 'RJSF_ADD_FORM';
export const RJSF_UPDATE_FORM = 'RJSF_UPDATE_FORM';
export const RJSF_REMOVE_FORM = 'RJSF_REMOVE_FORM';
export const RJSF_CHANGE_FORM_DATA = 'RJSF_CHANGE_FORM_DATA';
export const RJSF_INIT = 'RJSF_INIT';

export const RJSF_RESET = 'RJSF_RESET';

export const RJSF_SUBMIT = 'RJSF_SUBMIT';
export const RJSF_SUBMIT_REQUEST = 'RJSF_SUBMIT_REQUEST';
export const RJSF_SUBMIT_START = 'RJSF_SUBMIT_START';
export const RJSF_SUBMIT_SUCCESS = 'RJSF_SUBMIT_SUCCESS';
export const RJSF_SUBMIT_ERROR = 'RJSF_SUBMIT_ERROR';

export const RJSF_VALIDATE = 'RJSF_VALIDATE';
export const RJSF_VALIDATE_REQUEST = 'RJSF_VALIDATE_REQUEST';
export const RJSF_VALIDATE_START = 'RJSF_VALIDATE_START';
export const RJSF_VALIDATE_SUCCESS = 'RJSF_VALIDATE_SUCCESS';
export const RJSF_VALIDATE_ERROR = 'RJSF_VALIDATE_ERROR';
